<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dokter extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dokter_model');
    } 

    /*
     * Listing of dokter
     */
    function index()
    {
        $data['dokter'] = $this->Dokter_model->get_all_dokter();
        
        $data['_view'] = 'dokter/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new dokter
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nm_dokter' => $this->input->post('nm_dokter'),
				'jk' => $this->input->post('jk'),
				'tmp_lahir' => $this->input->post('tmp_lahir'),
				'tgl_lahir' => $this->input->post('tgl_lahir'),
				'gol_drh' => $this->input->post('gol_drh'),
				'agama' => $this->input->post('agama'),
				'almt_tgl' => $this->input->post('almt_tgl'),
				'no_telp' => $this->input->post('no_telp'),
				'stts_nikah' => $this->input->post('stts_nikah'),
				'kd_sps' => $this->input->post('kd_sps'),
				'alumni' => $this->input->post('alumni'),
				'no_ijn_praktek' => $this->input->post('no_ijn_praktek'),
				'status' => $this->input->post('status'),
            );
            
            $dokter_id = $this->Dokter_model->add_dokter($params);
            redirect('dokter/index');
        }
        else
        {            
            $data['_view'] = 'dokter/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a dokter
     */
    function edit($kd_dokter)
    {   
        // check if the dokter exists before trying to edit it
        $data['dokter'] = $this->Dokter_model->get_dokter($kd_dokter);
        
        if(isset($data['dokter']['kd_dokter']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nm_dokter' => $this->input->post('nm_dokter'),
					'jk' => $this->input->post('jk'),
					'tmp_lahir' => $this->input->post('tmp_lahir'),
					'tgl_lahir' => $this->input->post('tgl_lahir'),
					'gol_drh' => $this->input->post('gol_drh'),
					'agama' => $this->input->post('agama'),
					'almt_tgl' => $this->input->post('almt_tgl'),
					'no_telp' => $this->input->post('no_telp'),
					'stts_nikah' => $this->input->post('stts_nikah'),
					'kd_sps' => $this->input->post('kd_sps'),
					'alumni' => $this->input->post('alumni'),
					'no_ijn_praktek' => $this->input->post('no_ijn_praktek'),
					'status' => $this->input->post('status'),
                );

                $this->Dokter_model->update_dokter($kd_dokter,$params);            
                redirect('dokter/index');
            }
            else
            {
                $data['_view'] = 'dokter/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The dokter you are trying to edit does not exist.');
    } 

    /*
     * Deleting dokter
     */
    function remove($kd_dokter)
    {
        $dokter = $this->Dokter_model->get_dokter($kd_dokter);

        // check if the dokter exists before trying to delete it
        if(isset($dokter['kd_dokter']))
        {
            $this->Dokter_model->delete_dokter($kd_dokter);
            redirect('dokter/index');
        }
        else
            show_error('The dokter you are trying to delete does not exist.');
    }
    
    function json()
    {
        $this->load->library('datatables');
        $this->datatables->select('*');
        $this->datatables->from('dokter');
        return print_r($this->datatables->generate());
    }
}
