<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jns_perawatan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jns_perawatan_model');
    } 

    /*
     * Listing of jns_perawatan
     */
    function index()
    {
        $data['jns_perawatan'] = $this->Jns_perawatan_model->get_all_jns_perawatan();
        
        $data['_view'] = 'jns_perawatan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jns_perawatan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nm_perawatan' => $this->input->post('nm_perawatan'),
				'kd_kategori' => $this->input->post('kd_kategori'),
				'material' => $this->input->post('material'),
				'bhp' => $this->input->post('bhp'),
				'tarif_tindakandr' => $this->input->post('tarif_tindakandr'),
				'tarif_tindakanpr' => $this->input->post('tarif_tindakanpr'),
				'kso' => $this->input->post('kso'),
				'menejemen' => $this->input->post('menejemen'),
				'total_byrdr' => $this->input->post('total_byrdr'),
				'total_byrpr' => $this->input->post('total_byrpr'),
				'total_byrdrpr' => $this->input->post('total_byrdrpr'),
				'kd_pj' => $this->input->post('kd_pj'),
				'kd_poli' => $this->input->post('kd_poli'),
				'status' => $this->input->post('status'),
            );
            
            $jns_perawatan_id = $this->Jns_perawatan_model->add_jns_perawatan($params);
            redirect('jns_perawatan/index');
        }
        else
        {            
            $data['_view'] = 'jns_perawatan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jns_perawatan
     */
    function edit($kd_jenis_prw)
    {   
        // check if the jns_perawatan exists before trying to edit it
        $data['jns_perawatan'] = $this->Jns_perawatan_model->get_jns_perawatan($kd_jenis_prw);
        
        if(isset($data['jns_perawatan']['kd_jenis_prw']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nm_perawatan' => $this->input->post('nm_perawatan'),
					'kd_kategori' => $this->input->post('kd_kategori'),
					'material' => $this->input->post('material'),
					'bhp' => $this->input->post('bhp'),
					'tarif_tindakandr' => $this->input->post('tarif_tindakandr'),
					'tarif_tindakanpr' => $this->input->post('tarif_tindakanpr'),
					'kso' => $this->input->post('kso'),
					'menejemen' => $this->input->post('menejemen'),
					'total_byrdr' => $this->input->post('total_byrdr'),
					'total_byrpr' => $this->input->post('total_byrpr'),
					'total_byrdrpr' => $this->input->post('total_byrdrpr'),
					'kd_pj' => $this->input->post('kd_pj'),
					'kd_poli' => $this->input->post('kd_poli'),
					'status' => $this->input->post('status'),
                );

                $this->Jns_perawatan_model->update_jns_perawatan($kd_jenis_prw,$params);            
                redirect('jns_perawatan/index');
            }
            else
            {
                $data['_view'] = 'jns_perawatan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jns_perawatan you are trying to edit does not exist.');
    } 

    /*
     * Deleting jns_perawatan
     */
    function remove($kd_jenis_prw)
    {
        $jns_perawatan = $this->Jns_perawatan_model->get_jns_perawatan($kd_jenis_prw);

        // check if the jns_perawatan exists before trying to delete it
        if(isset($jns_perawatan['kd_jenis_prw']))
        {
            $this->Jns_perawatan_model->delete_jns_perawatan($kd_jenis_prw);
            redirect('jns_perawatan/index');
        }
        else
            show_error('The jns_perawatan you are trying to delete does not exist.');
    }
    
    function json()
    {
        $this->load->library('datatables');
        $this->datatables->select('*');
        $this->datatables->from('jns_perawatan');
        return print_r($this->datatables->generate());
    }
}
