<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pengajuan_kenaikan_tarif extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pengajuan_kenaikan_tarif_model');
    } 

    /*
     * Listing of pengajuan_kenaikan_tarif
     */
    function index()
    {
        $data['pengajuan_kenaikan_tarif'] = $this->Pengajuan_kenaikan_tarif_model->get_all_pengajuan_kenaikan_tarif();
        
        $data['_view'] = 'pengajuan_kenaikan_tarif/index';
        $this->renderLayout($data);
    }

    /*
     * Adding a new pengajuan_kenaikan_tarif
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'kd_dokter' => $this->input->post('kd_dokter'),
				'alasan' => $this->input->post('alasan'),
            );
            
            $pengajuan_kenaikan_tarif_id = $this->Pengajuan_kenaikan_tarif_model->add_pengajuan_kenaikan_tarif($params);
            redirect('pengajuan_kenaikan_tarif/index');
        }
        else
        {            
            $data['_view'] = 'pengajuan_kenaikan_tarif/add';
            $this->renderLayout($data);
        }
    }  

    /*
     * Editing a pengajuan_kenaikan_tarif
     */
    function edit($kd_pengajuan)
    {   
        // check if the pengajuan_kenaikan_tarif exists before trying to edit it
        $data['pengajuan_kenaikan_tarif'] = $this->Pengajuan_kenaikan_tarif_model->get_pengajuan_kenaikan_tarif($kd_pengajuan);
        
        if(isset($data['pengajuan_kenaikan_tarif']['kd_pengajuan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'kd_dokter' => $this->input->post('kd_dokter'),
					'alasan' => $this->input->post('alasan'),
                );

                $this->Pengajuan_kenaikan_tarif_model->update_pengajuan_kenaikan_tarif($kd_pengajuan,$params);            
                redirect('pengajuan_kenaikan_tarif/index');
            }
            else
            {
                $data['_view'] = 'pengajuan_kenaikan_tarif/edit';
                $this->renderLayout($data);
            }
        }
        else
            show_error('The pengajuan_kenaikan_tarif you are trying to edit does not exist.');
    } 

    /*
     * Deleting pengajuan_kenaikan_tarif
     */
    function remove($kd_pengajuan)
    {
        $pengajuan_kenaikan_tarif = $this->Pengajuan_kenaikan_tarif_model->get_pengajuan_kenaikan_tarif($kd_pengajuan);

        // check if the pengajuan_kenaikan_tarif exists before trying to delete it
        if(isset($pengajuan_kenaikan_tarif['kd_pengajuan']))
        {
            $this->Pengajuan_kenaikan_tarif_model->delete_pengajuan_kenaikan_tarif($kd_pengajuan);
            redirect('pengajuan_kenaikan_tarif/index');
        }
        else
            show_error('The pengajuan_kenaikan_tarif you are trying to delete does not exist.');
    }
    
    public function renderLayout($data)
    {
        $this->load->view('layout_tisla/header',$data);
        $this->load->view('layout_tisla/sidebar');
        $this->load->view('layout_tisla/maincontent');
        $this->load->view('layout_tisla/footer');
    }
}
