<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tarif_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tarif_master_model');
    } 

    /*
     * Listing of tarif_master
     */
    function index()
    {
        $data['tarif_master'] = $this->Tarif_master_model->get_all_tarif_master();
        
        $data['_view'] = 'tarif_master/index';
        $this->renderLayout($data);
    }

    /*
     * Adding a new tarif_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tipe_perawatan' => $this->input->post('tipe_perawatan'),
				'tarif' => $this->input->post('tarif'),
            );
            
            $tarif_master_id = $this->Tarif_master_model->add_tarif_master($params);
            redirect('tarif_master/index');
        }
        else
        {            
            $data['_view'] = 'tarif_master/add';
            $this->renderLayout($data);
        }
    }  

    /*
     * Editing a tarif_master
     */
    function edit($kd_tarif_master)
    {   
        // check if the tarif_master exists before trying to edit it
        $data['tarif_master'] = $this->Tarif_master_model->get_tarif_master($kd_tarif_master);
        
        if(isset($data['tarif_master']['kd_tarif_master']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tipe_perawatan' => $this->input->post('tipe_perawatan'),
					'tarif' => $this->input->post('tarif'),
                );

                $this->Tarif_master_model->update_tarif_master($kd_tarif_master,$params);            
                redirect('tarif_master/index');
            }
            else
            {
                $data['_view'] = 'tarif_master/edit';
                $this->renderLayout($data);
            }
        }
        else
            show_error('The tarif_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting tarif_master
     */
    function remove($kd_tarif_master)
    {
        $tarif_master = $this->Tarif_master_model->get_tarif_master($kd_tarif_master);

        // check if the tarif_master exists before trying to delete it
        if(isset($tarif_master['kd_tarif_master']))
        {
            $this->Tarif_master_model->delete_tarif_master($kd_tarif_master);
            redirect('tarif_master/index');
        }
        else
            show_error('The tarif_master you are trying to delete does not exist.');
    }
    
    public function renderLayout($data)
    {
        $this->load->view('layout_tisla/header',$data);
        $this->load->view('layout_tisla/sidebar');
        $this->load->view('layout_tisla/maincontent');
        $this->load->view('layout_tisla/footer');
    }
}
