<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tr_jasa_dokter extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tr_jasa_dokter_model');
    } 

    /*
     * Listing of tr_jasa_dokter
     */
    function index()
    {
        $data['tr_jasa_dokter'] = $this->Tr_jasa_dokter_model->get_all_tr_jasa_dokter();
        
        $data['_view'] = 'tr_jasa_dokter/index';
        $this->renderLayout($data);
    }

    /*
     * Adding a new tr_jasa_dokter
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tgl_transaksi' => $this->input->post('tgl_transaksi'),
				'kd_tarif_dokter' => $this->input->post('kd_tarif_dokter'),
            );
            
            $tr_jasa_dokter_id = $this->Tr_jasa_dokter_model->add_tr_jasa_dokter($params);
            redirect('tr_jasa_dokter/index');
        }
        else
        {            
            $data['_view'] = 'tr_jasa_dokter/add';
            $this->renderLayout($data);
        }
    }  

    /*
     * Editing a tr_jasa_dokter
     */
    function edit($kd_tr_dokter)
    {   
        // check if the tr_jasa_dokter exists before trying to edit it
        $data['tr_jasa_dokter'] = $this->Tr_jasa_dokter_model->get_tr_jasa_dokter($kd_tr_dokter);
        
        if(isset($data['tr_jasa_dokter']['kd_tr_dokter']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tgl_transaksi' => $this->input->post('tgl_transaksi'),
					'kd_tarif_dokter' => $this->input->post('kd_tarif_dokter'),
                );

                $this->Tr_jasa_dokter_model->update_tr_jasa_dokter($kd_tr_dokter,$params);            
                redirect('tr_jasa_dokter/index');
            }
            else
            {
                $data['_view'] = 'tr_jasa_dokter/edit';
                $this->renderLayout($data);
            }
        }
        else
            show_error('The tr_jasa_dokter you are trying to edit does not exist.');
    } 

    /*
     * Deleting tr_jasa_dokter
     */
    function remove($kd_tr_dokter)
    {
        $tr_jasa_dokter = $this->Tr_jasa_dokter_model->get_tr_jasa_dokter($kd_tr_dokter);

        // check if the tr_jasa_dokter exists before trying to delete it
        if(isset($tr_jasa_dokter['kd_tr_dokter']))
        {
            $this->Tr_jasa_dokter_model->delete_tr_jasa_dokter($kd_tr_dokter);
            redirect('tr_jasa_dokter/index');
        }
        else
            show_error('The tr_jasa_dokter you are trying to delete does not exist.');
    }
    
    public function renderLayout($data)
    {
        $this->load->view('layout_tisla/header',$data);
        $this->load->view('layout_tisla/sidebar');
        $this->load->view('layout_tisla/maincontent');
        $this->load->view('layout_tisla/footer');
    }
}
