<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jns_perawatan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jns_perawatan by kd_jenis_prw
     */
    function get_jns_perawatan($kd_jenis_prw)
    {
        return $this->db->get_where('jns_perawatan',array('kd_jenis_prw'=>$kd_jenis_prw))->row_array();
    }
        
    /*
     * Get all jns_perawatan
     */
    function get_all_jns_perawatan()
    {
        $this->db->order_by('kd_jenis_prw', 'desc');
        return $this->db->get('jns_perawatan')->result_array();
    }
        
    /*
     * function to add new jns_perawatan
     */
    function add_jns_perawatan($params)
    {
        $this->db->insert('jns_perawatan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jns_perawatan
     */
    function update_jns_perawatan($kd_jenis_prw,$params)
    {
        $this->db->where('kd_jenis_prw',$kd_jenis_prw);
        return $this->db->update('jns_perawatan',$params);
    }
    
    /*
     * function to delete jns_perawatan
     */
    function delete_jns_perawatan($kd_jenis_prw)
    {
        return $this->db->delete('jns_perawatan',array('kd_jenis_prw'=>$kd_jenis_prw));
    }
}
