<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tarif_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tarif_master by kd_tarif_master
     */
    function get_tarif_master($kd_tarif_master)
    {
        return $this->db->get_where('tarif_master',array('kd_tarif_master'=>$kd_tarif_master))->row_array();
    }
        
    /*
     * Get all tarif_master
     */
    function get_all_tarif_master()
    {
        $this->db->order_by('kd_tarif_master', 'desc');
        return $this->db->get('tarif_master')->result_array();
    }
        
    /*
     * function to add new tarif_master
     */
    function add_tarif_master($params)
    {
        $this->db->insert('tarif_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tarif_master
     */
    function update_tarif_master($kd_tarif_master,$params)
    {
        $this->db->where('kd_tarif_master',$kd_tarif_master);
        return $this->db->update('tarif_master',$params);
    }
    
    /*
     * function to delete tarif_master
     */
    function delete_tarif_master($kd_tarif_master)
    {
        return $this->db->delete('tarif_master',array('kd_tarif_master'=>$kd_tarif_master));
    }
}
