<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tr_jasa_dokter_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tr_jasa_dokter by kd_tr_dokter
     */
    function get_tr_jasa_dokter($kd_tr_dokter)
    {
        return $this->db->get_where('tr_jasa_dokter',array('kd_tr_dokter'=>$kd_tr_dokter))->row_array();
    }
        
    /*
     * Get all tr_jasa_dokter
     */
    function get_all_tr_jasa_dokter()
    {
        $this->db->order_by('kd_tr_dokter', 'desc');
        return $this->db->get('tr_jasa_dokter')->result_array();
    }
        
    /*
     * function to add new tr_jasa_dokter
     */
    function add_tr_jasa_dokter($params)
    {
        $this->db->insert('tr_jasa_dokter',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tr_jasa_dokter
     */
    function update_tr_jasa_dokter($kd_tr_dokter,$params)
    {
        $this->db->where('kd_tr_dokter',$kd_tr_dokter);
        return $this->db->update('tr_jasa_dokter',$params);
    }
    
    /*
     * function to delete tr_jasa_dokter
     */
    function delete_tr_jasa_dokter($kd_tr_dokter)
    {
        return $this->db->delete('tr_jasa_dokter',array('kd_tr_dokter'=>$kd_tr_dokter));
    }
}
