<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Type_tarif_perawatan_model extends CI_Model
{
    var $column_search = array('kd_type_prwtn','kd_jenis_perawatan','kd_tarif_master');
    var $column_order = array(null,'kd_type_prwtn','kd_jenis_perawatan','kd_tarif_master');
    var $order = array('kd_type_prwtn' => 'asc');
    
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get type_tarif_perawatan by kd_type_prwtn
     */
    function get_type_tarif_perawatan($kd_type_prwtn)
    {
        return $this->db->get_where('type_tarif_perawatan',array('kd_type_prwtn'=>$kd_type_prwtn))->row_array();
    }
        
    /*
     * Get all type_tarif_perawatan
     */
    function get_all_type_tarif_perawatan()
    {
        return $this->db->get('type_tarif_perawatan')->result();
    }
        
    /*
     * function to add new type_tarif_perawatan
     */
    function add_type_tarif_perawatan($params)
    {
        $this->db->insert('type_tarif_perawatan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update type_tarif_perawatan
     */
    function update_type_tarif_perawatan($kd_type_prwtn,$params)
    {
        $this->db->where('kd_type_prwtn',$kd_type_prwtn);
        return $this->db->update('type_tarif_perawatan',$params);
    }
    
    /*
     * function to delete type_tarif_perawatan
     */
    function delete_type_tarif_perawatan($kd_type_prwtn)
    {
        return $this->db->delete('type_tarif_perawatan',array('kd_type_prwtn'=>$kd_type_prwtn));
    }

    public function count_all()
    {
        $this->db->from('type_tarif_perawatan');
        return $this->db->count_all_results();
    }

    public function count_filtered()
    {
        $this->get_datatables_query();
        $query = $this->db->get();
        return $query->num_rows();
    }

    public function get_datatables()
    {
        $this->get_datatables_query();
        if ($_POST['length']!= -1)
            $this->db->limit($_POST['length'],$_POST['start']);
            $query = $this->db->get();
            return $query->result();
    }

    public function get_datatables_query()
    {
        $this->db->from('type_tarif_perawatan');
        $i =0;
        foreach ($this->column_search as $item) {
            if($_POST['search']['value']){
                if ($i === 0) {
                    $this->db->group_start();
                    $this->db->like($item,$_POST['search']['value']);
                }else {
                    $this->db->or_like($item,$_POST['search']['value']);
                }
                if (count($this->column_search)-1 == $i)
                    $this->db->group_end();
            }
            $i++;
        }
        if (isset($_POST['order'])) {
            $this->db->order_by($this->column_order[$_POST['order']['0']['column']],$_POST['order']['0']['dir']);
        }elseif (isset($this->order)) {
            $order = $this->order;
            $this->db->order_by(key($order),$order[key($order)]);
        }
    }
}
